약속 가능 날짜 등록 및 로그인 기능 추가
mju-likelion/interstellar pull request #7
Opened 2023-07-19 10:00 UTC by kMinsAlgorithm

- 약속 가능 날짜를 리스트로 전송할 경우 데이터 중복 확인 및 정렬 후 db에 저장하는 기능
- 회원가입과 동시에 토큰을 발생하는 기능
이 두 기능을 POST api/users에 구현해 두었습니다.

입력 값은 다음과 같습니다.
`{
  "roomCode": "12345",
  "userName": "민규",
  "password": "k4253425*",
  "dateOnly": true,
  "dates": [
    "2023-07-20",
    "2023-07-21",
    "2023-07-19",
    "2023-07-22",
    "2023-07-23",
    "2023-07-24",
    "2023-07-25",
    "2023-07-26",
    "2023-07-27",
    "2023-07-28"
  ]
}
`

2023-07-19 15:58 UTC, ndaemy requested changes
일단 큼직한 것부터 리뷰해두었습니다. 저거 수정되고 나면 다시 확인해볼게요!

2023-07-19 15:58 UTC, ndaemy commented on src/api/users/users.service.ts
> +  async createAppointement(createAppointmentDto: CreateAppointmentDto) {
오타있어여

```suggestion
  async createAppointment(createAppointmentDto: CreateAppointmentDto) {
```

2023-07-19 15:58 UTC, ndaemy commented on src/api/users/users.service.ts
> +      !(await this.prismaService.room.findUnique({ where: { code: roomCode } }))
제 작업이랑 겹치는 부분이라 이러셨던거 같긴 한데, roomService 를 쓰는게 나을거 같습니다

2023-07-19 15:58 UTC, ndaemy commented on src/api/users/users.service.ts
> +    if (await this.prismaService.user.findUnique({ where: { userName } })) {
이것도 userService 에 findOne 메서드 하나 만들어서 쓰는게 나을 것 같아여

2023-07-19 15:58 UTC, ndaemy commented on src/api/users/users.service.ts
> +      //userName 중복 확인
이런 쉬운건 오히려 주석이 불필요할 것 같아요!

2023-07-19 15:58 UTC, ndaemy commented on prisma/schema.prisma
> +  userName    String @unique
username 이 더 익숙하신가여 userName 이 더 익숙하신가여?

2023-07-19 16:01 UTC, kMinsAlgorithm commented on prisma/schema.prisma
> +  userName    String @unique
username을 하니 where문에 적용을 할 수 없게 되더리구요..
파라미터를 비꾸면 되긴 하는데 camelCase?지킨다는 명분하에 변경했습니다

2023-07-19 16:01 UTC, kMinsAlgorithm commented on src/api/users/users.service.ts
> +  async createAppointement(createAppointmentDto: CreateAppointmentDto) {
수정하겠습니다

2023-07-19 16:01 UTC, kMinsAlgorithm commented on src/api/users/users.service.ts
> +      !(await this.prismaService.room.findUnique({ where: { code: roomCode } }))
앗 이부분은 이해가 되지 않습니다

2023-07-19 16:03 UTC, kMinsAlgorithm reviewed
리뷰 확인했습니다
적용해보겠습니다

2023-07-20 23:30 UTC, kMinsAlgorithm commented on src/api/users/users.service.ts
> +      !(await this.prismaService.room.findUnique({ where: { code: roomCode } }))
적용해보겠습니다!

2023-07-23 06:21 UTC, ndaemy approved these changes
리뷰는 몇 개 남겼지만, 기능적으로 이슈는 없을 것 같아 approve 합니다! 이번에 머지하고 다음에 리팩토링해도 무방할 것 같아서요!

2023-07-23 06:21 UTC, ndaemy commented on src/api/users/dto/create-appointment.dto.ts
> +  @Matches(/^[A-Za-z0-9!@#$%^&*()]{8,30}$/)
이거 이 Regex인지는 디자이너님한테 물어보고 해야 할 것 같아요!

2023-07-23 06:21 UTC, ndaemy commented on src/api/users/dto/create-appointment.dto.ts
> +  @IsString({ each: true })
오홍 👍

2023-07-23 06:21 UTC, ndaemy commented on src/api/users/dto/update-user.dto.ts
> +export class UpdateUserDto extends PartialType(CreateAppointmentDto) {}
이게 이 타입이 맞을까요? 예를 들어서 username 이나 password 는 업데이트 되는 경우의 수가 없을 것 같아서요!

2023-07-23 06:21 UTC, ndaemy commented on src/api/users/users.service.ts
> +    const errors404 = [];
차라리 badRequestErros / notFoundErrors 가 더 가독성 좋은 네이밍일 것 같아요!

2023-07-26 05:31 UTC, kMinsAlgorithm commented on src/api/users/dto/create-appointment.dto.ts
> +  @Matches(/^[A-Za-z0-9!@#$%^&*()]{8,30}$/)
넵 제가 여쭤보겠습니다

2023-07-26 05:32 UTC, kMinsAlgorithm commented on src/api/users/dto/update-user.dto.ts
> +export class UpdateUserDto extends PartialType(CreateAppointmentDto) {}
음 제가 수정을 안했군요...ㅎㅎ Patch user/api 들어갈때 수정하도록 하겠습니다..ㅎ

2023-07-26 05:58 UTC, merged