PATCH api/users 기능 추가
mju-likelion/interstellar pull request #8
Opened 2023-07-26 08:52 UTC by kMinsAlgorithm

PATCH api/users 기능 추가하였습니다.

요청 형식은

**query params**
roomCode 

**Body** 
username
dateOnly
dates

입니다.

2023-08-05 11:41 UTC, ndaemy requested changes
Query Params 건 때문에 Request changes 로 남깁니다 빠샤 💪

2023-08-05 11:41 UTC, ndaemy commented on src/api/users/users.controller.ts
> +    @Query('roomCode') roomCode: string,
이거 Query 가 아니라 Params 여야 합니다!
그.. 피그마에 [여기](https://www.figma.com/file/MVnWUEQdAJiwbJQRaRm0fL/%EB%A9%8B%EC%82%AC_2%EC%B0%A8-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8?type=design&node-id=2313%3A21343&mode=dev) 확인해보시면 이해가실거에요!

2023-08-05 11:41 UTC, ndaemy commented on src/api/users/users.service.ts
> +  async isDateOnlyFormatValid(dateOnly: boolean, dates: string[]) {
1. 얘는 private method 로 만들면 좋을 것 같고,
2. private method 는 맨 위든 맨 밑이든 한 쪽으로 몰면 좋을 것 같아요!

2023-08-08 10:32 UTC, kMinsAlgorithm commented
코드 리뷰 기반하여 수정 완료했습니다.
수정 사항은 다음과 같습니다.
1. Query -> Param
2. 사용하지 않은 라이브러리 삭제
3. isDateOnlyFormatValid 함수 private로 지정

2023-08-08 19:32 UTC, ndaemy approved these changes
수고하셨습니다 👏

2023-08-08 19:32 UTC, ndaemy commented on src/api/users/users.service.ts
> +    console.log(roomCode);
나중에 시간 되면 이런 테스트 코드는 삭제시켜주시면 좋을듯!

2023-08-09 05:59 UTC, merged